version: '3'
services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: webapp
    ports:
      - "9000:9000"
    depends_on:
      - mongo
    restart: always
    networks:
      - coinlist
  mongo:
    image: mongo
    container_name: mongo
    environment:
      - MONGO_INITDB_DATABASE=base
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=204411
    networks:
      - coinlist
    volumes:
      - mongo:/data/db
networks:
  coinlist:
    driver: bridge

volumes:
  mongo: